### ISSUE TITLE
Document the needed Datastructures for Celestial Objects

### ISSUE THREAD

**Issue by DomiMartinGlogi** [DomiMartinGlogi/magnetar_game#2]
See title.

The following structure might be interesting for each object:

```yaml
# Definition for a star system
StarSystem:
   Sol:
      type: STAR
      mass: 1.988416x10^30
      radius: 6.957x10^8
      parentTo:
           - Mercury:
              type: PLANET_ROCKY
              semi-major-axis: 57'910'000
              eccentricity: 0.205630
              atmosphere: # Would be a list but Mercury doesn't have one lol
```
Obviously mass, radius and the list of child objects would also duplicate down into children
